version: '3.8'

services:
  web:
    build: .
    container_name: finca_app
    expose:
      - "5001"
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DATABASE_URL=postgresql+psycopg://admin:julyanna23@postgres-db:5432/master_db
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true
